#
# Module manifest for module 'HelloWorld' that is not actually ready to use.
#
# Generated by: Katie Kodes
#
# Generated on: 6/24/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'HelloWorld.psm1'

    # Source code lists ModuleVersion as "0.0.0" as a stand-in.  Use the "Version" option when we run Build-Module with a real version number.
    ModuleVersion = '0.0.0'

    # ID used to uniquely identify this module
    GUID = 'fd62e5a8-c3c7-4553-a3d4-1d50ec16133e'

    # Author of this module
    Author            = 'Katie Kodes'

    # Company or vendor of this module
    CompanyName       = 'Katie Kodes'

    # Copyright statement for this module
    Copyright         = '(c) 2025 Katie Kodes. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Powershell module build and publish automation demonstration'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '7.0'

    # This module only includes functions, so only "FunctionsToExport" is included.
    FunctionsToExport = '*'
}

